/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#00d1ff',
        'surface-variant': '#2d3449',
        'on-surface': '#dae2fd',
        'primary-fixed': '#b7eaff',
        'surface': '#0b1326',
        'on-secondary-fixed': '#271900',
        'on-primary-fixed': '#001f28',
        'secondary-fixed-dim': '#ffba20',
        'outline-variant': '#3c494e',
        'on-secondary': '#412d00',
        'background': '#0b1326',
        'secondary-fixed': '#ffdea8',
        'surface-container-highest': '#2d3449',
        'surface-container': '#171f33',
        'inverse-primary': '#00677f',
        'primary-fixed-dim': '#4cd6ff',
        'surface-bright': '#31394d',
        'outline': '#859399',
        'error': '#ffb4ab',
        'tertiary': '#ffd59c',
        'surface-container-low': '#131b2e',
        'secondary-container': '#feb700',
        'on-primary-container': '#00566a',
        'surface-dim': '#0b1326',
        'primary': '#a4e6ff',
        'on-surface-variant': '#bbc9cf',
        'tertiary-container': '#feb127',
        'on-primary': '#003543',
        'surface-container-high': '#222a3d',
        'on-background': '#dae2fd',
        'secondary': '#ffdb9d',
        'surface-tint': '#4cd6ff',
        'surface-container-lowest': '#060e20',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}

